### ISSUE TITLE
AutoStart is not working

### ISSUE THREAD

**Issue by grkadam7** [MrTheGood/WordGamesPlus#5]
This is my config file https://pastebin.com/Wf1qqgU5
The games are not auto starting even if there are more people online than needed.

Please let me know if I did any mistakes while editing conifg

**Comment by MrTheGood** [comment]
Hey NightFury, 

Thank you for reporting! I unfortunately do not see any immediate issues that could be causing this. 
Would you mind telling me what server version you're on, whether you're using Spigot, Paper, or something else, and what some of the other plugins are that you use? 

Thanks in advance!

**Comment by grkadam7** [comment]
Server version is 1.18.2 and it's papermc

I reinstalled the plugin and now the auto start is working
